version: "3.9"

services:
    mssql:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        container_name: mssql-server
        environment:
            SA_PASSWORD: "P@ssw0rd"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"

    comic-shop-api:
        container_name: comic-shop-api
        restart: "on-failure:5"
        build: 
            context: ./
            dockerfile: ./Dockerfile
        ports:
            - "8080:80"
        depends_on:
            - mssql
        environment:
            ConnectionStrings__ComicShopContext: "Data Source=comicshopdb.czcs6c06wtdx.sa-east-1.rds.amazonaws.com,1433;Initial Catalog=comicshopdb;User ID=admin;Password=wF1nKLNbY5V2W73xPLqW"
            ElasticSearch__Uri: "http://host.docker.internal:9200"
        extra_hosts:
            - "host.docker.internal:host-gateway"